-- AlterTable
ALTER TABLE "AlertRule" ADD COLUMN "categoria" TEXT NOT NULL DEFAULT 'REGISTRAL';
ALTER TABLE "AlertRule" ADD COLUMN "alcance" TEXT NOT NULL DEFAULT 'TODAS';
ALTER TABLE "AlertRule" ADD COLUMN "createdAt" DATETIME NOT NULL DEFAULT '2026-03-01 00:00:00';
ALTER TABLE "AlertRule" ADD COLUMN "updatedAt" DATETIME NOT NULL DEFAULT '2026-03-01 00:00:00';
ALTER TABLE "AlertRule" ADD COLUMN "createdById" TEXT;
ALTER TABLE "AlertRule" ADD COLUMN "updatedById" TEXT;
